### ISSUE TITLE
ability to overwrite id='active'

### ISSUE THREAD

**Issue by gebrits** [itemslide/itemslide.github.io#11]
In a lot of circumstances id=`active` is not ideal. The most simplest case as having multiple sliders on the page: 2 DOM-elements end up getting id=`active` which is not compliant. 

What about a way to overwrite this behavior, or (and this may work well enough) generate some id's and keep a list of those generated. I.e.: `itemslide-1`, `itemslide-2`. etc.

**Comment by nir9** [comment]
Yah but maybe a simpler solution would be to do class=active instead.

**Comment by gebrits** [comment]
Yeah sure, didn't look at why you needed it. Still may I suggest using a namespaced classname such as `itemslide-active` instead, so it will play nice with other libraries?

**Comment by nir9** [comment]
Sure I'll add it
