### ISSUE TITLE
Anchor (Click event) not firing

### ISSUE THREAD

**Issue by shinbonlin** [itemslide/itemslide.github.io#13]
HTML:

Javascript:

$(document).ready(function () {

    $("#blogslide ul").itemslide({
        one_item: true //Set this for proper full screen navigation
    }); //initialize itemslide

    $(window).resize(function () {
        $("#blogslide ul").reload();

    }); //Recalculate width and center positions and sizes when window is resized

    $('#blogslide a').click(function(e){
            e.preventDefault();
            console.log("this is the click");
        });
});

Test Link 1 is working.
Test Link 2 is not working and MouseOver, Click event is not fired

Jquery version: 1.11.2

**Comment by nir9** [comment]
Can you please provide a JSFiddle example so it'll be easier to check

**Comment by shinbonlin** [comment]
Thank you. But I tested it on http://codepen.io/anon/pen/RPWaZK

It works! Not work on my Localhost server. it's strange.

**Comment by nir9** [comment]
I'll test on my local server and see if it works

**Comment by shinbonlin** [comment]
Sorry! My mistake. A transparent layer is on the DIV, I didn't notice it.

Thank you very much for providing such great plugin!

**Comment by nir9** [comment]
:+1:
