### ISSUE TITLE
Howto Vanilla + Browserify

### ISSUE THREAD

**Issue by loranger** [itemslide/itemslide.github.io#15]
I'm trying to make itemslide work within a [vue.js](http://vuejs.org/) app.
I used npm in order to install itemslider, then with browserify I tried
```javascript
var itemslide = require("itemslide")
```
but it didn't work because I don't use/need jQuery.

So i did copy the itemslide.vanilla.min.js inside my app and tried to
```javascript
var itemslide = require("./itemslide.vanilla.min.js")
```
but it failed because `itemslide is not a function`.

I tried
```javascript
global.itemslide = require("./itemslide.vanilla.min.js")
```
and
```javascript
module.exports = require("./itemslide.vanilla.min.js")
```

but none works.

Did I miss somethnig ? Is there any clue on using vanilla itemslide and browserify ?

**Comment by nir9** [comment]
Hi,
I still haven't made itemslide compatible with Browserify but i will add this with a guide on how to setup.
In the mean time you can include itemslide globally as a script tag.

**Comment by f0rmat1k** [comment]
nir9 maybe just something like
```js
if (typeof exports === 'object') {
    module.exports = Itemslide;
}
```
is enough for browserify? No need to include [that polyfill](https://github.com/itemslide/itemslide.github.io/commit/40b4b46cf41824a79f414f8de5086f33a3e9179a#diff-e82c927ae496103735acf91e44c2bb36R1) and separate into modules.

**Comment by nir9** [comment]
Vanilla is no longer supported.
ItemSlide requires jQuery or Zepto.
If you want it with Browserify just include ItemSlide and jQuery globally as a script tag.
