### ISSUE TITLE
Strange behavior with mousewheel

### ISSUE THREAD

**Issue by f0rmat1k** [itemslide/itemslide.github.io#16]
To fast scrolling with wheel, specialy when using trackpad on macOS. You just can't to scroll 1 slide, allways 2 and more.
I propose to look at our solution [wheel-indicator](https://github.com/Promo/wheel-indicator). One movement = one slide.

**Comment by nir9** [comment]
Hi,
Your library looks cool but i don't think it would be a very good experience if it scrolls one at time - if it had some feature that would allow to set scrolling speed (and scroll regularly like jquery-mousewheel) than i would definitely consider using your solution instead.

**Comment by f0rmat1k** [comment]
@nir9 yes, but you can easy tune, how slides should be scrolled by one movement.
new WheelIndicator({
```javascript
new WheelIndicator({
    elem: document.querySelector('.element'),
    callback: function(e){
         carousel.gotoSlide(/* logic here */)
    }
  });
```

Right now it's really hard to use carousel with some mouses and trackpads (depend on device and the frequency of firing events)

**Comment by nir9** [comment]
I still don't think it would be a good experience of it scrolling a couple of slides per scroll.
Unless there would be the feature that i suggested earlier i don't think this would fit.

**Comment by f0rmat1k** [comment]
ok
