### ISSUE TITLE
Two finger swipe is super sensitive on mac

### ISSUE THREAD

**Issue by madole** [itemslide/itemslide.github.io#17]
The smallest of movements on a macbook touchpad swipes 2 or more slides at a time. A debounce should fix this so it only reacts to every x events fired.

**Comment by nir9** [comment]
Thanks,
I'll if debounce will fix this.

**Comment by f0rmat1k** [comment]
@madole you can try to use [wheel-indicator](https://github.com/Promo/wheel-indicator) in conjunction with itemslide.

**Comment by madole** [comment]
@f0rmat1k that's pushing the control of the native functionality to the implementation, that's inherently wrong

**Comment by f0rmat1k** [comment]
@madole Yes, but depend on situation. If you use fullscreen slides (100% screen width or height) and move one slide per gesture, the use of wheel-indicator is justified.

**Comment by nir9** [comment]
Updated the touchpad swiping, now its less sensitive.
