### ISSUE TITLE
HTC One Android 4.1.1 Default browser

### ISSUE THREAD

**Issue by f0rmat1k** [itemslide/itemslide.github.io#18]
Don't work.
Also demo on site looks bad.

**Comment by nir9** [comment]
Try using chrome.

**Comment by f0rmat1k** [comment]
@nir9 shure it works on Chrome) But Chrome is not available on all devices, and not all users use it. I'l try to debug and send PR later,

**Comment by nir9** [comment]
Thanks.
I can't test on every single browser therefore there may some that don't work properly, but i did make sure that it works on the popular ones.
