### ISSUE TITLE
Changing .itemslide-active while moving

### ISSUE THREAD

**Issue by MeMyselfI** [itemslide/itemslide.github.io#20]
Currently, the CSS class is set when the movement is done.
I need a CSS class which is updated while dragging so the user can adjust the exact position before releasing his finger. This might be another CSS class like .itemslide-currently-active if you wish to.

**Comment by nir9** [comment]
Sure on the next update.

**Comment by MeMyselfI** [comment]
Thanks.

**Comment by nir9** [comment]
Ok i have decided not to add this feature directly to the plugin but i added a new external function that enables you to implement this - here is an example:


```js
// Example of setting current active index as dragging
    carousel.on('changePos', function(event) {
        var currentIndex = carousel.getIndexByPosition(carousel.getCurrentPos());
        console.log("dragging active index: "+ currentIndex);
        carousel.children().removeClass('itemslide-currently-active');
        carousel.children(':nth-child(' + ((currentIndex + 1) || 0) + ')').addClass('itemslide-currently-active');
    });
```

**Comment by f0rmat1k** [comment]
@nir9 myabe children().eq((currentIndex + 1) || 0) is simpler?

**Comment by f0rmat1k** [comment]
ah, it's just example

**Comment by MeMyselfI** [comment]
But there's no getIndexByPosition implemented, is it?

**Comment by nir9** [comment]
I haven't documented it yet but I added this external function to the plugin so you can use it.
