### ISSUE TITLE
Copyright and permission notice are not included in 

### ISSUE THREAD

**Issue by ceenlrnjim** [itemslide/itemslide.github.io#21]
According to the MIT license in your License file, "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software", but the uglified versions you list for download do not include the notices.  Does this mean that I am in violation of the MIT license if I distribute those files as part of my application?

**Comment by nir9** [comment]
Oh i haven't noticed that, i'll add the license to the dist version next commit.
For now if you want you can just put the license alongside the file.
