### ISSUE TITLE
Why $.fn.itemslide placed into $.ready?

### ISSUE THREAD

**Issue by f0rmat1k** [itemslide/itemslide.github.io#29]
e.g. my builder builded so:
```js
$(function(){
    $('.slider').itemslide();
});
...
$(function(){
   $.fn.itemslide = function(){
    ///...
   }
});
```

And i get error `itemslide is not a function`. So itemslide requires to be included before all, which is not always feasible. The above example actually happened to me. I think plugin users should make a decision about how to initialize itself. You don't think so?

**Comment by nir9** [comment]
You're right i'll just get rid of document ready.
