### ISSUE TITLE
Scrolling trigged by vertical double finger swipe on Macbook is override

### ISSUE THREAD

**Issue by hy9be** [itemslide/itemslide.github.io#30]
My HTML is
```html
<div id="frame">
            <ul>
                <li>
                    <div class="content"></div>
                </li>
                <li>
                    <div class="content"></div>
                </li>
            </ul>
        </div>
```
And the Javascript code is:
```javascript
var carousel;
        $(document).ready(function () {

            carousel = $("#frame ul");

            carousel.itemslide({
                disable_scroll: false,
            }); //initialize itemslide

            $(window).resize(function () {
                carousel.reload();

            }); //Recalculate width and center positions and sizes when window is resized
        });
```

But no matter what direction I do the double finger swipe, the <li> will slide. The default scrolling action for ``div#content`` is override.

**Comment by nir9** [comment]
Well you can disable mousewheel sliding on the carousel using the options so that it wont override the default scrolling.

**Comment by hy9be** [comment]
Thanks @nir9 ! But I did not find any options related in the doc: http://itemslide.github.io/docs/. Could you please shed some lights?

**Comment by nir9** [comment]
You can disable mousewheel sliding using the option ``disable_scroll``

**Comment by hy9be** [comment]
It worked, thanks! The wording in the doc is a bit confusing though. I created a PR to improve the doc here: https://github.com/itemslide/itemslide.github.io/pull/31. Please take a look if that helps.
