### ISSUE TITLE
Difference between click and swipe

### ISSUE THREAD

**Issue by maartenmachiels** [itemslide/itemslide.github.io#33]
Hi

I'd like to include an event on tapping / clicking on a slide. 
In my setup, I have a list of images that I'd love to enlarge upon click.

As of now, swiping also triggers the onclick event, so I have to include another button, which complicates things.
You can see an example here: http://beta.jackie-lee.com/mcgregor/during.html

Is there any way to programmatically find the difference between swipe and click?
Thanks in advance for your remarks. Everything works very nicely I might add.

**Comment by nir9** [comment]
Yah I can add an event "clickSlide", I'll work on it for next update.
Glad to hear :)

**Comment by maartenmachiels** [comment]
Thanks a bunch! Would be great to see this. My client is excited!

Op vr 14 aug. 2015 om 18:02 schreef nir9 <notifications@github.com>:

**Comment by nir9** [comment]
Added.

**Comment by maartenmachiels** [comment]
Wow man, you're great. Will implement in the coming days and let you know.
BTW, you should get your plugin into unheap:
http://www.unheap.com/section/media/sliders-carousels/

Op vr 14 aug. 2015 om 21:25 schreef nir9 <notifications@github.com>:

**Comment by nir9** [comment]
Yah i'll try getting the plugin into unheap

**Comment by maartenmachiels** [comment]
Heads up, I've added a question on StackOverflow for the implementation of something concerning ItemSlide. If you want to score some reputation: head over to http://stackoverflow.com/questions/32052955/itemslide-fancybox-supersized
