### ISSUE TITLE
Set start and end Point

### ISSUE THREAD

**Issue by Jeff0029** [itemslide/itemslide.github.io#34]
I was wondering if someone know how to make the first item stick to the left instead of the middle when selected (same for the right).  I found a way to do it but it cut the velocity to 0 when the animation reach the limit.

Thank you.

**Comment by nir9** [comment]
Hi this option is currently unavailable but I do plan to add this in future updates.

**Comment by Jeff0029** [comment]
in the meantime I was able to nearly do it myself! lol
When my work is done I could show you my additions.

**Comment by nir9** [comment]
Oh cool - if you want you can also fork this repo, add your additions and then create a pull request.

**Comment by Jeff0029** [comment]
Hello nir9

I'm almost done setting up my pull request when I was testing the addSlide method.
Is it already broken?  When I call it it adds the slide inside the last <li>.

Everything else is smooth sailing.

**Comment by nir9** [comment]
Yah looks like the method is already broken i'll fix it next update, thanks for the heads up.
