### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by MeMyselfI** [itemslide/itemslide.github.io#36]
Because of the tanslate3d, text is very blurry. Isn't it possible to translateX and translateY to avoid this?

**Comment by nir9** [comment]
Nope cuz translate3d uses hardware acceleration to achieve smoother animations read here:
http://trinhtrunganh.com/translate3d-vs-translate-performance/
I don't see how the text is "very blurry" as i put text in the examples and they look just fine.

**Comment by MeMyselfI** [comment]
This is true for mobile Devices but I guess this isn't a big issue on desktop browsers.
Here you can see the difference with my page: http://fs1.directupload.net/images/150920/8zhvgtfj.png

**Comment by nir9** [comment]
Hmm weird, on my mobile device (Android Chrome) the text is not blurry at all.

**Comment by MeMyselfI** [comment]
It's not blurry on Firefox Desktop, too. Just checked Safari on iOS 9 and it's not blurry, too. Seems to be a Chrome problem...
