### ISSUE TITLE
addSlide not functioning correctly

### ISSUE THREAD

**Issue by innoville** [itemslide/itemslide.github.io#42]
'addSlide(data)' does not seem to be working as expected.
1. When a line "carousel.addSlide("TEST");"  is added to sliding.js, the <li> element with "TEST" is appended as a child of the last <li> element.
2. An error occurs, and it says that b.reload (carousel.reload in itemslide.js) is not a function.
Would you be able to take a look ?
Thank you.

![addslide](https://cloud.githubusercontent.com/assets/9953874/11926688/223d9698-a80a-11e5-889d-fcef11461461.PNG)

**Comment by nir9** [comment]
Yah i see, i'll fix asap

**Comment by nir9** [comment]
Fixed.
