### ISSUE TITLE
addSlide with drag events

### ISSUE THREAD

**Issue by PurHur** [itemslide/itemslide.github.io#47]
If im adding slides (because i have to load them...) they dont have the events for dragging...

The relead function didnt update the events at all.

Sorry i'm not able to make a nice fix for this. I had to patch it very hard in your code :/

**Comment by PurHur** [comment]
hmm found a solution

My patch... See Line ~415
// Start navigation listeners
    $el.on('mousedown touchstart','>*', function (e) {

**Comment by nir9** [comment]
Thanks!
