### ISSUE TITLE
Prev & next Buttons

### ISSUE THREAD

**Issue by HGraf89** [itemslide/itemslide.github.io#50]
Is there anyone who uses prev and next buttons in itemslide.js?

Need help.

**Comment by nir9** [comment]
What's the problem?

**Comment by HGraf89** [comment]
Hi,

didn´t found something about prev and next buttons for itemslider.js. 
I´m not so much fit in JS.

Do you have an example for me?

Thanks

Am 18.02.2016 um 17:45 schrieb Nir Lichtman:

**Comment by nir9** [comment]
I'll add an example for next and prev buttons.

**Comment by PurHur** [comment]
Not so hard.

    $('#prevButton').on('click',function () {
      slider.previous();
    });

and there is nothing wrong with this function.

**Comment by nir9** [comment]
I added a new example with prev and next buttons: http://itemslide.github.io/examples/buttons_carousel/
