### ISSUE TITLE
Clamp to half width if outer container contains an even number of elements

### ISSUE THREAD

**Issue by PurHur** [itemslide/itemslide.github.io#54]
The items will clamp to the half width if the outer container contains (in the visible part) an even number of elements. If its uneven it works perfect. 

Did anybody encounter this problem before?

**Comment by PurHur** [comment]
The bug is in **getPositionByIndex**

        return -(i * slides.children().outerWidth(true) - ((slides.parent().outerWidth(true) - slides.children().outerWidth(true)) / 2))


i think the **/ 2** is only useful if the slider is **not** a **left_sided**.

**Comment by nir9** [comment]
I don't really get the problem i'm now testing and i see no problem when there is an even amount of elements. can you provide an example that doesn't work (jsfiddle or something)?

**Comment by PurHur** [comment]
Here you go:
http://jsfiddle.net/k0vh8jwc/1/

**Comment by nir9** [comment]
Ok i see, i'll work on a fix.

**Comment by nir9** [comment]
Added your fix, thanks.
