### ISSUE TITLE
change names for "next()" & "previous()"

### ISSUE THREAD

**Issue by artemsky** [itemslide/itemslide.github.io#55]
change names for "next()" & "previous()" due "next()" has conflict with "jquery.next()"

do somthing like
nextSlide()
prevSlide()

**Comment by nir9** [comment]
sure next update

**Comment by bobmagicii** [comment]
i am guessing this never happened.

`$.fn.next=function(){this.gotoSlide(this.data("vars")`

trying to traverse my dom >_>

**Comment by nir9** [comment]
Solved, use the "remove_deprecated_external_functions" option to remove deprecated functions, and use the new nextSlide and previousSlide functions.
