### ISSUE TITLE
Destroy the slider ? Method .destroy()

### ISSUE THREAD

**Issue by CrucifixArnaud** [itemslide/itemslide.github.io#56]
Hi, 

I would like to totally destroy() the slider (I only use the slider on a specific screen-size), to avoid issue on screen resize. I would like to destroy the slider, and reinit it on a other breakpoint.

But I don't found any .destroy() method? 

Any idea ? Plan to implement one ?

Thanks.

**Comment by PurHur** [comment]
use remove();

**Comment by nir9** [comment]
:point_up_2:
