### ISSUE TITLE
changePos event is running continuously

### ISSUE THREAD

**Issue by szegheo** [itemslide/itemslide.github.io#59]
See the bug in action:
http://codepen.io/szegheo/pen/RadbRe?editors=1111

Scripts, html, css are the same versions that you use on your demo page (http://itemslide.github.io/index.html)

However typing this code to the console on your demo page it works as excepted. 
```javascript
$("ul").on('changePos', function(e) { console.log(e.timeStamp) });
```
strange...

**Comment by szegheo** [comment]
Same in latest Chrome, Edge, FF...

**Comment by nir9** [comment]
idk but this works: http://codepen.io/anon/pen/aZOYvP?editors=1111
