### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by maartenmachiels** [itemslide/itemslide.github.io#61]
Hi

Is there any way to enable pinch to zoom on mobile devices? In my application, my users sometimes want to zoom into an image in the itemslide carousel. I notice that this is not possible. I've tested on Android and iPhone.

Take for example [https://itemslide.github.io/](https://itemslide.github.io/) If you try to zoom in, it will not work. Any idea's?

**Comment by maartenmachiels** [comment]
Any update on this?

**Comment by nir9** [comment]
You can't zoom in the carousel because it causes problems with the swiping, but you can remove this meta line and enable zooming in any other area in the page:
```<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />```

**Comment by maartenmachiels** [comment]
Okay, thanks!

Op za 4 jun. 2016 14:12 schreef Nir Lichtman <notifications@github.com>:
