### ISSUE TITLE
'Active' setting not working as expected

### ISSUE THREAD

**Issue by info-steppenwolf** [itemslide/itemslide.github.io#65]
Thanks for a superb carousel. I revisited the docs and determined that to re-set the default active slide I have to add "start: '2', ( or whatever the slide number is, counting from 0). This is not working as expected- dunno if I did something wrong. The advantage of being able to set an altered view is that the visitor likely will end up swiping in both directions and hopefully, linger longer. Thanks for any pointers about how this can be done. My settings:

<script>
                    $(window).load(function() {
                        $("#scrolling ul").itemslide({
                            disable_clicktoslide: 'false',
                            disable_slide: 'false',
                            one_item: 'true',
                            parent_width: false,
                            duration: '350',
                            swipe_sensitivity: '290',
                            disable_autowidth: true,
                            swipe_out: false,
                            start:'2',
                        });

                    });
                </script>

**Comment by nir9** [comment]
Hi,
Here is a working example: http://jsbin.com/mesivoleya/edit?html,css,js,output
didn't work because you need to give the parameter start the number 2 and not the string '2'.

**Comment by info-steppenwolf** [comment]
Thanks!
