### ISSUE TITLE
Increasing the performance in Cordova Native App

### ISSUE THREAD

**Issue by zenmano** [itemslide/itemslide.github.io#7]
I am using this in an hybrid mobile Application. When converted into corresponding native app, It works a bit ok in top end mobile such as nexus and all. But When it comes to a bit normal mobile, the transition is very slow. The feel of touch looks clumsy. Can you please suggest some ways where transition does not slow. I am really in need of this.(duration is already set 25ms)

**Comment by nir9** [comment]
Closing due to no answer and that the plugin has changed a lot since this issue.
