### ISSUE TITLE
Multiple sliders: only one options array

### ISSUE THREAD

**Issue by RomanWu** [itemslide/itemslide.github.io#86]
When creating multiple sliders with different options on the same page, they all get the same options.

Example:
`carousel1 = $(".class1 ul");
carousel1.itemslide({
  left_sided: false,
  duration:500
});

carousel2 = $('.class2 ul');
carousel2.itemslide({
  left_sided: true,
  duration:100
});`

**Expected result:**
One slider to the left with 100 duration, the other slider centered with 500 duration.

**Actual result:**
Both sliders get the second options, in this example "true" and 100.

**Fix:**
I'm guessing, the carousel.create function needs the following change. This works for me.

before:
_this.options = options;

after:
_this.options = $.extend({}, options);

**Comment by nir9** [comment]
Thanks for reporting :)
